name: IXBL-test-action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  single:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Step one
      - run: echo "step one"

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: "511476692"
          token: "5163585819:AAHU1_JxgzOCbI4ox67tpsx_RauzAphgwXo"
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}