name: IXBL-mytest-action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  single:
    runs-on: ubuntu-latest

    steps:
      - name: Step two
      - uses: actions/checkout@v3
      - run: echo "Hello"