name: IXBL-test-action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  single:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Step one
        run: echo "step one"
